/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionRecord {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
  'course' : string,
}
export interface Announcement {
  'id' : bigint,
  'title' : string,
  'postedBy' : string,
  'content' : string,
  'timestamp' : bigint,
}
export interface BrochureRequest {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
  'phone' : string,
  'courseName' : string,
  'courseId' : bigint,
}
export interface BrochureUrl {
  'id' : bigint,
  'url' : string,
  'courseId' : bigint,
  'urlType' : string,
}
export interface ContactRecord {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface Course {
  'id' : bigint,
  'fee' : string,
  'title' : string,
  'duration' : string,
  'description' : string,
  'isActive' : boolean,
  'colorKey' : string,
  'topics' : Array<string>,
  'badge' : string,
  'subtitle' : string,
}
export interface CourseLead {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'downloadCount' : bigint,
  'phone' : string,
  'courseName' : string,
  'courseId' : bigint,
}
export interface FranchiseLead {
  'id' : bigint,
  'leadType' : string,
  'city' : string,
  'name' : string,
  'investment' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'downloadCount' : bigint,
  'phone' : string,
}
export interface FranchiseRecord {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'investment' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface UserProfile {
  'id' : bigint,
  'username' : string,
  'enrolledDate' : bigint,
  'password' : string,
  'role' : string,
  'fullName' : string,
  'isActive' : boolean,
  'email' : string,
  'progress' : bigint,
  'phone' : string,
  'course' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAnnouncement' : ActorMethod<[string, string, string], { 'ok' : bigint }>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<
    [string, string, string, string, string, string, Array<string>, string],
    bigint
  >,
  'deleteAnnouncement' : ActorMethod<[bigint], boolean>,
  'deleteCourse' : ActorMethod<[bigint], boolean>,
  'getAdmissions' : ActorMethod<[], { 'ok' : Array<AdmissionRecord> }>,
  'getAllLeads' : ActorMethod<
    [],
    {
      'courseLeads' : Array<CourseLead>,
      'franchiseLeads' : Array<FranchiseLead>,
    }
  >,
  'getAllStudents' : ActorMethod<[], { 'ok' : Array<UserProfile> }>,
  'getAnnouncements' : ActorMethod<[], { 'ok' : Array<Announcement> }>,
  'getBrochureRequests' : ActorMethod<[], Array<BrochureRequest>>,
  'getBrochureUrlByCourseId' : ActorMethod<[bigint], [] | [BrochureUrl]>,
  'getBrochureUrls' : ActorMethod<[], Array<BrochureUrl>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessages' : ActorMethod<[], { 'ok' : Array<ContactRecord> }>,
  'getCourses' : ActorMethod<[], { 'ok' : Array<Course> }>,
  'getFranchiseBrochureUrl' : ActorMethod<[], [] | [BrochureUrl]>,
  'getFranchiseInquiries' : ActorMethod<[], { 'ok' : Array<FranchiseRecord> }>,
  'getStudentProgress' : ActorMethod<[string], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfileByUsername' : ActorMethod<[string], { 'ok' : UserProfile }>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<[string, string], { 'ok' : UserProfile }>,
  'registerUser' : ActorMethod<
    [string, string, string, string, string, string],
    { 'ok' : UserProfile }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBrochureUrl' : ActorMethod<[bigint, string, string], boolean>,
  'submitAdmission' : ActorMethod<
    [string, string, string, string, string, string],
    { 'ok' : bigint }
  >,
  'submitBrochureRequest' : ActorMethod<
    [string, string, string, [] | [bigint], string],
    bigint
  >,
  'submitContact' : ActorMethod<
    [string, string, string, string],
    { 'ok' : bigint }
  >,
  'submitCourseLead' : ActorMethod<
    [string, string, string, bigint, string, string],
    bigint
  >,
  'submitFranchiseInquiry' : ActorMethod<
    [string, string, string, string, string, string],
    { 'ok' : bigint }
  >,
  'submitFranchiseLead' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'trackDownload' : ActorMethod<[bigint, string], boolean>,
  'updateCourse' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
    ],
    boolean
  >,
  'updateStudentProgress' : ActorMethod<[string, bigint], boolean>,
  'updateUserProfile' : ActorMethod<
    [string, string, string, string],
    { 'ok' : UserProfile }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];