/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdmissionRecord = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});
export const CourseLead = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'downloadCount' : IDL.Nat,
  'phone' : IDL.Text,
  'courseName' : IDL.Text,
  'courseId' : IDL.Nat,
});
export const FranchiseLead = IDL.Record({
  'id' : IDL.Nat,
  'leadType' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'investment' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'downloadCount' : IDL.Nat,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'enrolledDate' : IDL.Int,
  'password' : IDL.Text,
  'role' : IDL.Text,
  'fullName' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'progress' : IDL.Nat,
  'phone' : IDL.Text,
  'course' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'postedBy' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const BrochureRequest = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'courseName' : IDL.Text,
  'courseId' : IDL.Nat,
});
export const BrochureUrl = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'courseId' : IDL.Nat,
  'urlType' : IDL.Text,
});
export const ContactRecord = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'fee' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'colorKey' : IDL.Text,
  'topics' : IDL.Vec(IDL.Text),
  'badge' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const FranchiseRecord = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'investment' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Nat })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCourse' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCourse' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAdmissions' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Vec(AdmissionRecord) })],
      ['query'],
    ),
  'getAllLeads' : IDL.Func(
      [],
      [
        IDL.Record({
          'courseLeads' : IDL.Vec(CourseLead),
          'franchiseLeads' : IDL.Vec(FranchiseLead),
        }),
      ],
      ['query'],
    ),
  'getAllStudents' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Vec(UserProfile) })],
      ['query'],
    ),
  'getAnnouncements' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Vec(Announcement) })],
      ['query'],
    ),
  'getBrochureRequests' : IDL.Func([], [IDL.Vec(BrochureRequest)], ['query']),
  'getBrochureUrlByCourseId' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(BrochureUrl)],
      ['query'],
    ),
  'getBrochureUrls' : IDL.Func([], [IDL.Vec(BrochureUrl)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessages' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Vec(ContactRecord) })],
      ['query'],
    ),
  'getCourses' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Vec(Course) })],
      ['query'],
    ),
  'getFranchiseBrochureUrl' : IDL.Func([], [IDL.Opt(BrochureUrl)], ['query']),
  'getFranchiseInquiries' : IDL.Func(
      [],
      [IDL.Record({ 'ok' : IDL.Vec(FranchiseRecord) })],
      ['query'],
    ),
  'getStudentProgress' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfileByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'ok' : UserProfile })],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : UserProfile })],
      ['query'],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : UserProfile })],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBrochureUrl' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
  'submitAdmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Nat })],
      [],
    ),
  'submitBrochureRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Nat })],
      [],
    ),
  'submitCourseLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitFranchiseInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Nat })],
      [],
    ),
  'submitFranchiseLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'trackDownload' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateCourse' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateStudentProgress' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : UserProfile })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdmissionRecord = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  const CourseLead = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'downloadCount' : IDL.Nat,
    'phone' : IDL.Text,
    'courseName' : IDL.Text,
    'courseId' : IDL.Nat,
  });
  const FranchiseLead = IDL.Record({
    'id' : IDL.Nat,
    'leadType' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'investment' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'downloadCount' : IDL.Nat,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'enrolledDate' : IDL.Int,
    'password' : IDL.Text,
    'role' : IDL.Text,
    'fullName' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'progress' : IDL.Nat,
    'phone' : IDL.Text,
    'course' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'postedBy' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const BrochureRequest = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'courseName' : IDL.Text,
    'courseId' : IDL.Nat,
  });
  const BrochureUrl = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'courseId' : IDL.Nat,
    'urlType' : IDL.Text,
  });
  const ContactRecord = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'fee' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'colorKey' : IDL.Text,
    'topics' : IDL.Vec(IDL.Text),
    'badge' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const FranchiseRecord = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'investment' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Nat })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCourse' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCourse' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAdmissions' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Vec(AdmissionRecord) })],
        ['query'],
      ),
    'getAllLeads' : IDL.Func(
        [],
        [
          IDL.Record({
            'courseLeads' : IDL.Vec(CourseLead),
            'franchiseLeads' : IDL.Vec(FranchiseLead),
          }),
        ],
        ['query'],
      ),
    'getAllStudents' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Vec(UserProfile) })],
        ['query'],
      ),
    'getAnnouncements' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Vec(Announcement) })],
        ['query'],
      ),
    'getBrochureRequests' : IDL.Func([], [IDL.Vec(BrochureRequest)], ['query']),
    'getBrochureUrlByCourseId' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BrochureUrl)],
        ['query'],
      ),
    'getBrochureUrls' : IDL.Func([], [IDL.Vec(BrochureUrl)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessages' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Vec(ContactRecord) })],
        ['query'],
      ),
    'getCourses' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Vec(Course) })],
        ['query'],
      ),
    'getFranchiseBrochureUrl' : IDL.Func([], [IDL.Opt(BrochureUrl)], ['query']),
    'getFranchiseInquiries' : IDL.Func(
        [],
        [IDL.Record({ 'ok' : IDL.Vec(FranchiseRecord) })],
        ['query'],
      ),
    'getStudentProgress' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfileByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'ok' : UserProfile })],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : UserProfile })],
        ['query'],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : UserProfile })],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBrochureUrl' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Bool], []),
    'submitAdmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Nat })],
        [],
      ),
    'submitBrochureRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Nat })],
        [],
      ),
    'submitCourseLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitFranchiseInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Nat })],
        [],
      ),
    'submitFranchiseLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'trackDownload' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'updateCourse' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateStudentProgress' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : UserProfile })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };